FROM phpswoole/swoole:5-php8.2-alpine

# Install PHP extensions needed by CI4
RUN apk add --no-cache bash icu-dev oniguruma-dev libzip-dev autoconf gcc g++ make \
    && docker-php-ext-install pdo_mysql intl mbstring zip \
    && apk del autoconf gcc g++ make

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

EXPOSE 9501
