export const countries = [
  { code: 'TW', name: '台灣', en: 'Taiwan' },
  { code: 'CN', name: '中國大陸', en: 'China' },
  { code: 'HK', name: '香港', en: 'Hong Kong' },
  { code: 'MO', name: '澳門', en: 'Macao' },
  { code: 'JP', name: '日本', en: 'Japan' },
  { code: 'KR', name: '韓國', en: 'South Korea' },
  { code: 'SG', name: '新加坡', en: 'Singapore' },
  { code: 'US', name: '美國', en: 'United States' },
  { code: 'GB', name: '英國', en: 'United Kingdom' },
  { code: 'AU', name: '澳大利亞', en: 'Australia' },
  { code: 'CA', name: '加拿大', en: 'Canada' },
  { code: 'AF', name: '阿富汗', en: 'Afghanistan' },
  { code: 'AL', name: '阿爾巴尼亞', en: 'Albania' },
  { code: 'DZ', name: '阿爾及利亞', en: 'Algeria' },
  { code: 'AD', name: '安道爾', en: 'Andorra' },
  { code: 'AO', name: '安哥拉', en: 'Angola' },
  { code: 'AG', name: '安提瓜和巴布達', en: 'Antigua and Barbuda' },
  { code: 'AR', name: '阿根廷', en: 'Argentina' },
  { code: 'AM', name: '亞美尼亞', en: 'Armenia' },
  { code: 'AT', name: '奧地利', en: 'Austria' },
  { code: 'AZ', name: '亞塞拜然', en: 'Azerbaijan' },
  { code: 'BS', name: '巴哈馬', en: 'Bahamas' },
  { code: 'BH', name: '巴林', en: 'Bahrain' },
  { code: 'BD', name: '孟加拉', en: 'Bangladesh' },
  { code: 'BB', name: '巴貝多', en: 'Barbados' },
  { code: 'BY', name: '白俄羅斯', en: 'Belarus' },
  { code: 'BE', name: '比利時', en: 'Belgium' },
  { code: 'BZ', name: '貝里斯', en: 'Belize' },
  { code: 'BJ', name: '貝南', en: 'Benin' },
  { code: 'BT', name: '不丹', en: 'Bhutan' },
  { code: 'BO', name: '玻利維亞', en: 'Bolivia' },
  { code: 'BA', name: '波士尼亞與赫塞哥維納', en: 'Bosnia and Herzegovina' },
  { code: 'BW', name: '波札那', en: 'Botswana' },
  { code: 'BR', name: '巴西', en: 'Brazil' },
  { code: 'BN', name: '汶萊', en: 'Brunei' },
  { code: 'BG', name: '保加利亞', en: 'Bulgaria' },
  { code: 'BF', name: '布吉納法索', en: 'Burkina Faso' },
  { code: 'BI', name: '蒲隆地', en: 'Burundi' },
  { code: 'CV', name: '維德角', en: 'Cape Verde' },
  { code: 'KH', name: '柬埔寨', en: 'Cambodia' },
  { code: 'CM', name: '喀麥隆', en: 'Cameroon' },
  { code: 'CF', name: '中非共和國', en: 'Central African Republic' },
  { code: 'TD', name: '查德', en: 'Chad' },
  { code: 'CL', name: '智利', en: 'Chile' },
  { code: 'CO', name: '哥倫比亞', en: 'Colombia' },
  { code: 'KM', name: '科摩羅', en: 'Comoros' },
  { code: 'CG', name: '剛果共和國', en: 'Republic of the Congo' },
  { code: 'CD', name: '剛果民主共和國', en: 'DR Congo' },
  { code: 'CR', name: '哥斯大黎加', en: 'Costa Rica' },
  { code: 'CI', name: '象牙海岸', en: "Côte d'Ivoire" },
  { code: 'HR', name: '克羅埃西亞', en: 'Croatia' },
  { code: 'CU', name: '古巴', en: 'Cuba' },
  { code: 'CY', name: '賽普勒斯', en: 'Cyprus' },
  { code: 'CZ', name: '捷克', en: 'Czech Republic' },
  { code: 'DK', name: '丹麥', en: 'Denmark' },
  { code: 'DJ', name: '吉布地', en: 'Djibouti' },
  { code: 'DM', name: '多米尼克', en: 'Dominica' },
  { code: 'DO', name: '多明尼加共和國', en: 'Dominican Republic' },
  { code: 'EC', name: '厄瓜多', en: 'Ecuador' },
  { code: 'EG', name: '埃及', en: 'Egypt' },
  { code: 'SV', name: '薩爾瓦多', en: 'El Salvador' },
  { code: 'GQ', name: '赤道幾內亞', en: 'Equatorial Guinea' },
  { code: 'ER', name: '厄利垂亞', en: 'Eritrea' },
  { code: 'EE', name: '愛沙尼亞', en: 'Estonia' },
  { code: 'SZ', name: '史瓦帝尼', en: 'Eswatini' },
  { code: 'ET', name: '衣索比亞', en: 'Ethiopia' },
  { code: 'FJ', name: '斐濟', en: 'Fiji' },
  { code: 'FI', name: '芬蘭', en: 'Finland' },
  { code: 'FR', name: '法國', en: 'France' },
  { code: 'GA', name: '加彭', en: 'Gabon' },
  { code: 'GM', name: '甘比亞', en: 'Gambia' },
  { code: 'GE', name: '喬治亞', en: 'Georgia' },
  { code: 'DE', name: '德國', en: 'Germany' },
  { code: 'GH', name: '迦納', en: 'Ghana' },
  { code: 'GR', name: '希臘', en: 'Greece' },
  { code: 'GD', name: '格瑞那達', en: 'Grenada' },
  { code: 'GT', name: '瓜地馬拉', en: 'Guatemala' },
  { code: 'GN', name: '幾內亞', en: 'Guinea' },
  { code: 'GW', name: '幾內亞比索', en: 'Guinea-Bissau' },
  { code: 'GY', name: '蓋亞那', en: 'Guyana' },
  { code: 'HT', name: '海地', en: 'Haiti' },
  { code: 'HN', name: '宏都拉斯', en: 'Honduras' },
  { code: 'HU', name: '匈牙利', en: 'Hungary' },
  { code: 'IS', name: '冰島', en: 'Iceland' },
  { code: 'IN', name: '印度', en: 'India' },
  { code: 'ID', name: '印尼', en: 'Indonesia' },
  { code: 'IR', name: '伊朗', en: 'Iran' },
  { code: 'IQ', name: '伊拉克', en: 'Iraq' },
  { code: 'IE', name: '愛爾蘭', en: 'Ireland' },
  { code: 'IL', name: '以色列', en: 'Israel' },
  { code: 'IT', name: '義大利', en: 'Italy' },
  { code: 'JM', name: '牙買加', en: 'Jamaica' },
  { code: 'JO', name: '約旦', en: 'Jordan' },
  { code: 'KZ', name: '哈薩克', en: 'Kazakhstan' },
  { code: 'KE', name: '肯亞', en: 'Kenya' },
  { code: 'KI', name: '吉里巴斯', en: 'Kiribati' },
  { code: 'KW', name: '科威特', en: 'Kuwait' },
  { code: 'KG', name: '吉爾吉斯', en: 'Kyrgyzstan' },
  { code: 'LA', name: '寮國', en: 'Laos' },
  { code: 'LV', name: '拉脫維亞', en: 'Latvia' },
  { code: 'LB', name: '黎巴嫩', en: 'Lebanon' },
  { code: 'LS', name: '賴索托', en: 'Lesotho' },
  { code: 'LR', name: '賴比瑞亞', en: 'Liberia' },
  { code: 'LY', name: '利比亞', en: 'Libya' },
  { code: 'LI', name: '列支敦斯登', en: 'Liechtenstein' },
  { code: 'LT', name: '立陶宛', en: 'Lithuania' },
  { code: 'LU', name: '盧森堡', en: 'Luxembourg' },
  { code: 'MG', name: '馬達加斯加', en: 'Madagascar' },
  { code: 'MW', name: '馬拉威', en: 'Malawi' },
  { code: 'MY', name: '馬來西亞', en: 'Malaysia' },
  { code: 'MV', name: '馬爾地夫', en: 'Maldives' },
  { code: 'ML', name: '馬利', en: 'Mali' },
  { code: 'MT', name: '馬爾他', en: 'Malta' },
  { code: 'MH', name: '馬紹爾群島', en: 'Marshall Islands' },
  { code: 'MR', name: '茅利塔尼亞', en: 'Mauritania' },
  { code: 'MU', name: '模里西斯', en: 'Mauritius' },
  { code: 'MX', name: '墨西哥', en: 'Mexico' },
  { code: 'FM', name: '密克羅尼西亞', en: 'Micronesia' },
  { code: 'MD', name: '摩爾多瓦', en: 'Moldova' },
  { code: 'MC', name: '摩納哥', en: 'Monaco' },
  { code: 'MN', name: '蒙古', en: 'Mongolia' },
  { code: 'ME', name: '蒙特內哥羅', en: 'Montenegro' },
  { code: 'MA', name: '摩洛哥', en: 'Morocco' },
  { code: 'MZ', name: '莫三比克', en: 'Mozambique' },
  { code: 'MM', name: '緬甸', en: 'Myanmar' },
  { code: 'NA', name: '納米比亞', en: 'Namibia' },
  { code: 'NR', name: '諾魯', en: 'Nauru' },
  { code: 'NP', name: '尼泊爾', en: 'Nepal' },
  { code: 'NL', name: '荷蘭', en: 'Netherlands' },
  { code: 'NZ', name: '紐西蘭', en: 'New Zealand' },
  { code: 'NI', name: '尼加拉瓜', en: 'Nicaragua' },
  { code: 'NE', name: '尼日', en: 'Niger' },
  { code: 'NG', name: '奈及利亞', en: 'Nigeria' },
  { code: 'MK', name: '北馬其頓', en: 'North Macedonia' },
  { code: 'NO', name: '挪威', en: 'Norway' },
  { code: 'OM', name: '阿曼', en: 'Oman' },
  { code: 'PK', name: '巴基斯坦', en: 'Pakistan' },
  { code: 'PW', name: '帛琉', en: 'Palau' },
  { code: 'PA', name: '巴拿馬', en: 'Panama' },
  { code: 'PG', name: '巴布亞紐幾內亞', en: 'Papua New Guinea' },
  { code: 'PY', name: '巴拉圭', en: 'Paraguay' },
  { code: 'PE', name: '秘魯', en: 'Peru' },
  { code: 'PH', name: '菲律賓', en: 'Philippines' },
  { code: 'PL', name: '波蘭', en: 'Poland' },
  { code: 'PT', name: '葡萄牙', en: 'Portugal' },
  { code: 'QA', name: '卡達', en: 'Qatar' },
  { code: 'RO', name: '羅馬尼亞', en: 'Romania' },
  { code: 'RU', name: '俄羅斯', en: 'Russia' },
  { code: 'RW', name: '盧安達', en: 'Rwanda' },
  { code: 'KN', name: '聖克里斯多福及尼維斯', en: 'Saint Kitts and Nevis' },
  { code: 'LC', name: '聖露西亞', en: 'Saint Lucia' },
  { code: 'VC', name: '聖文森及格瑞那丁', en: 'Saint Vincent and the Grenadines' },
  { code: 'WS', name: '薩摩亞', en: 'Samoa' },
  { code: 'SM', name: '聖馬利諾', en: 'San Marino' },
  { code: 'ST', name: '聖多美普林西比', en: 'São Tomé and Príncipe' },
  { code: 'SA', name: '沙烏地阿拉伯', en: 'Saudi Arabia' },
  { code: 'SN', name: '塞內加爾', en: 'Senegal' },
  { code: 'RS', name: '塞爾維亞', en: 'Serbia' },
  { code: 'SC', name: '塞席爾', en: 'Seychelles' },
  { code: 'SL', name: '獅子山', en: 'Sierra Leone' },
  { code: 'SK', name: '斯洛伐克', en: 'Slovakia' },
  { code: 'SI', name: '斯洛維尼亞', en: 'Slovenia' },
  { code: 'SB', name: '索羅門群島', en: 'Solomon Islands' },
  { code: 'SO', name: '索馬利亞', en: 'Somalia' },
  { code: 'ZA', name: '南非', en: 'South Africa' },
  { code: 'SS', name: '南蘇丹', en: 'South Sudan' },
  { code: 'ES', name: '西班牙', en: 'Spain' },
  { code: 'LK', name: '斯里蘭卡', en: 'Sri Lanka' },
  { code: 'SD', name: '蘇丹', en: 'Sudan' },
  { code: 'SR', name: '蘇利南', en: 'Suriname' },
  { code: 'SE', name: '瑞典', en: 'Sweden' },
  { code: 'CH', name: '瑞士', en: 'Switzerland' },
  { code: 'SY', name: '敘利亞', en: 'Syria' },
  { code: 'TJ', name: '塔吉克', en: 'Tajikistan' },
  { code: 'TZ', name: '坦尚尼亞', en: 'Tanzania' },
  { code: 'TH', name: '泰國', en: 'Thailand' },
  { code: 'TL', name: '東帝汶', en: 'Timor-Leste' },
  { code: 'TG', name: '多哥', en: 'Togo' },
  { code: 'TO', name: '東加', en: 'Tonga' },
  { code: 'TT', name: '千里達及托巴哥', en: 'Trinidad and Tobago' },
  { code: 'TN', name: '突尼西亞', en: 'Tunisia' },
  { code: 'TR', name: '土耳其', en: 'Turkey' },
  { code: 'TM', name: '土庫曼', en: 'Turkmenistan' },
  { code: 'TV', name: '吐瓦魯', en: 'Tuvalu' },
  { code: 'UG', name: '烏干達', en: 'Uganda' },
  { code: 'UA', name: '烏克蘭', en: 'Ukraine' },
  { code: 'AE', name: '阿拉伯聯合大公國', en: 'United Arab Emirates' },
  { code: 'UY', name: '烏拉圭', en: 'Uruguay' },
  { code: 'UZ', name: '烏茲別克', en: 'Uzbekistan' },
  { code: 'VU', name: '萬那杜', en: 'Vanuatu' },
  { code: 'VE', name: '委內瑞拉', en: 'Venezuela' },
  { code: 'VN', name: '越南', en: 'Vietnam' },
  { code: 'YE', name: '葉門', en: 'Yemen' },
  { code: 'ZM', name: '尚比亞', en: 'Zambia' },
  { code: 'ZW', name: '辛巴威', en: 'Zimbabwe' },
]

/**
 * 根據語系取得國家顯示名稱
 * @param {Object} country - country object from countries array
 * @param {string} locale - current locale (e.g. 'zh-TW', 'en')
 */
export function getCountryName(country, locale) {
  if (locale === 'en') return country.en
  return country.name
}
