export const countries = [
  { code: 'TW', name: '台灣', en: 'Taiwan', dialCode: '+886' },
  { code: 'CN', name: '中國大陸', en: 'China', dialCode: '+86' },
  { code: 'HK', name: '香港', en: 'Hong Kong', dialCode: '+852' },
  { code: 'MO', name: '澳門', en: 'Macao', dialCode: '+853' },
  { code: 'JP', name: '日本', en: 'Japan', dialCode: '+81' },
  { code: 'KR', name: '韓國', en: 'South Korea', dialCode: '+82' },
  { code: 'SG', name: '新加坡', en: 'Singapore', dialCode: '+65' },
  { code: 'US', name: '美國', en: 'United States', dialCode: '+1' },
  { code: 'GB', name: '英國', en: 'United Kingdom', dialCode: '+44' },
  { code: 'AU', name: '澳大利亞', en: 'Australia', dialCode: '+61' },
  { code: 'CA', name: '加拿大', en: 'Canada', dialCode: '+1' },
  { code: 'AF', name: '阿富汗', en: 'Afghanistan', dialCode: '+93' },
  { code: 'AL', name: '阿爾巴尼亞', en: 'Albania', dialCode: '+355' },
  { code: 'DZ', name: '阿爾及利亞', en: 'Algeria', dialCode: '+213' },
  { code: 'AD', name: '安道爾', en: 'Andorra', dialCode: '+376' },
  { code: 'AO', name: '安哥拉', en: 'Angola', dialCode: '+244' },
  { code: 'AG', name: '安提瓜和巴布達', en: 'Antigua and Barbuda', dialCode: '+1268' },
  { code: 'AR', name: '阿根廷', en: 'Argentina', dialCode: '+54' },
  { code: 'AM', name: '亞美尼亞', en: 'Armenia', dialCode: '+374' },
  { code: 'AT', name: '奧地利', en: 'Austria', dialCode: '+43' },
  { code: 'AZ', name: '亞塞拜然', en: 'Azerbaijan', dialCode: '+994' },
  { code: 'BS', name: '巴哈馬', en: 'Bahamas', dialCode: '+1242' },
  { code: 'BH', name: '巴林', en: 'Bahrain', dialCode: '+973' },
  { code: 'BD', name: '孟加拉', en: 'Bangladesh', dialCode: '+880' },
  { code: 'BB', name: '巴貝多', en: 'Barbados', dialCode: '+1246' },
  { code: 'BY', name: '白俄羅斯', en: 'Belarus', dialCode: '+375' },
  { code: 'BE', name: '比利時', en: 'Belgium', dialCode: '+32' },
  { code: 'BZ', name: '貝里斯', en: 'Belize', dialCode: '+501' },
  { code: 'BJ', name: '貝南', en: 'Benin', dialCode: '+229' },
  { code: 'BT', name: '不丹', en: 'Bhutan', dialCode: '+975' },
  { code: 'BO', name: '玻利維亞', en: 'Bolivia', dialCode: '+591' },
  { code: 'BA', name: '波士尼亞與赫塞哥維納', en: 'Bosnia and Herzegovina', dialCode: '+387' },
  { code: 'BW', name: '波札那', en: 'Botswana', dialCode: '+267' },
  { code: 'BR', name: '巴西', en: 'Brazil', dialCode: '+55' },
  { code: 'BN', name: '汶萊', en: 'Brunei', dialCode: '+673' },
  { code: 'BG', name: '保加利亞', en: 'Bulgaria', dialCode: '+359' },
  { code: 'BF', name: '布吉納法索', en: 'Burkina Faso', dialCode: '+226' },
  { code: 'BI', name: '蒲隆地', en: 'Burundi', dialCode: '+257' },
  { code: 'CV', name: '維德角', en: 'Cape Verde', dialCode: '+238' },
  { code: 'KH', name: '柬埔寨', en: 'Cambodia', dialCode: '+855' },
  { code: 'CM', name: '喀麥隆', en: 'Cameroon', dialCode: '+237' },
  { code: 'CF', name: '中非共和國', en: 'Central African Republic', dialCode: '+236' },
  { code: 'TD', name: '查德', en: 'Chad', dialCode: '+235' },
  { code: 'CL', name: '智利', en: 'Chile', dialCode: '+56' },
  { code: 'CO', name: '哥倫比亞', en: 'Colombia', dialCode: '+57' },
  { code: 'KM', name: '科摩羅', en: 'Comoros', dialCode: '+269' },
  { code: 'CG', name: '剛果共和國', en: 'Republic of the Congo', dialCode: '+242' },
  { code: 'CD', name: '剛果民主共和國', en: 'DR Congo', dialCode: '+243' },
  { code: 'CR', name: '哥斯大黎加', en: 'Costa Rica', dialCode: '+506' },
  { code: 'CI', name: '象牙海岸', en: "Côte d'Ivoire", dialCode: '+225' },
  { code: 'HR', name: '克羅埃西亞', en: 'Croatia', dialCode: '+385' },
  { code: 'CU', name: '古巴', en: 'Cuba', dialCode: '+53' },
  { code: 'CY', name: '賽普勒斯', en: 'Cyprus', dialCode: '+357' },
  { code: 'CZ', name: '捷克', en: 'Czech Republic', dialCode: '+420' },
  { code: 'DK', name: '丹麥', en: 'Denmark', dialCode: '+45' },
  { code: 'DJ', name: '吉布地', en: 'Djibouti', dialCode: '+253' },
  { code: 'DM', name: '多米尼克', en: 'Dominica', dialCode: '+1767' },
  { code: 'DO', name: '多明尼加共和國', en: 'Dominican Republic', dialCode: '+1809' },
  { code: 'EC', name: '厄瓜多', en: 'Ecuador', dialCode: '+593' },
  { code: 'EG', name: '埃及', en: 'Egypt', dialCode: '+20' },
  { code: 'SV', name: '薩爾瓦多', en: 'El Salvador', dialCode: '+503' },
  { code: 'GQ', name: '赤道幾內亞', en: 'Equatorial Guinea', dialCode: '+240' },
  { code: 'ER', name: '厄利垂亞', en: 'Eritrea', dialCode: '+291' },
  { code: 'EE', name: '愛沙尼亞', en: 'Estonia', dialCode: '+372' },
  { code: 'SZ', name: '史瓦帝尼', en: 'Eswatini', dialCode: '+268' },
  { code: 'ET', name: '衣索比亞', en: 'Ethiopia', dialCode: '+251' },
  { code: 'FJ', name: '斐濟', en: 'Fiji', dialCode: '+679' },
  { code: 'FI', name: '芬蘭', en: 'Finland', dialCode: '+358' },
  { code: 'FR', name: '法國', en: 'France', dialCode: '+33' },
  { code: 'GA', name: '加彭', en: 'Gabon', dialCode: '+241' },
  { code: 'GM', name: '甘比亞', en: 'Gambia', dialCode: '+220' },
  { code: 'GE', name: '喬治亞', en: 'Georgia', dialCode: '+995' },
  { code: 'DE', name: '德國', en: 'Germany', dialCode: '+49' },
  { code: 'GH', name: '迦納', en: 'Ghana', dialCode: '+233' },
  { code: 'GR', name: '希臘', en: 'Greece', dialCode: '+30' },
  { code: 'GD', name: '格瑞那達', en: 'Grenada', dialCode: '+1473' },
  { code: 'GT', name: '瓜地馬拉', en: 'Guatemala', dialCode: '+502' },
  { code: 'GN', name: '幾內亞', en: 'Guinea', dialCode: '+224' },
  { code: 'GW', name: '幾內亞比索', en: 'Guinea-Bissau', dialCode: '+245' },
  { code: 'GY', name: '蓋亞那', en: 'Guyana', dialCode: '+592' },
  { code: 'HT', name: '海地', en: 'Haiti', dialCode: '+509' },
  { code: 'HN', name: '宏都拉斯', en: 'Honduras', dialCode: '+504' },
  { code: 'HU', name: '匈牙利', en: 'Hungary', dialCode: '+36' },
  { code: 'IS', name: '冰島', en: 'Iceland', dialCode: '+354' },
  { code: 'IN', name: '印度', en: 'India', dialCode: '+91' },
  { code: 'ID', name: '印尼', en: 'Indonesia', dialCode: '+62' },
  { code: 'IR', name: '伊朗', en: 'Iran', dialCode: '+98' },
  { code: 'IQ', name: '伊拉克', en: 'Iraq', dialCode: '+964' },
  { code: 'IE', name: '愛爾蘭', en: 'Ireland', dialCode: '+353' },
  { code: 'IL', name: '以色列', en: 'Israel', dialCode: '+972' },
  { code: 'IT', name: '義大利', en: 'Italy', dialCode: '+39' },
  { code: 'JM', name: '牙買加', en: 'Jamaica', dialCode: '+1876' },
  { code: 'JO', name: '約旦', en: 'Jordan', dialCode: '+962' },
  { code: 'KZ', name: '哈薩克', en: 'Kazakhstan', dialCode: '+7' },
  { code: 'KE', name: '肯亞', en: 'Kenya', dialCode: '+254' },
  { code: 'KI', name: '吉里巴斯', en: 'Kiribati', dialCode: '+686' },
  { code: 'KW', name: '科威特', en: 'Kuwait', dialCode: '+965' },
  { code: 'KG', name: '吉爾吉斯', en: 'Kyrgyzstan', dialCode: '+996' },
  { code: 'LA', name: '寮國', en: 'Laos', dialCode: '+856' },
  { code: 'LV', name: '拉脫維亞', en: 'Latvia', dialCode: '+371' },
  { code: 'LB', name: '黎巴嫩', en: 'Lebanon', dialCode: '+961' },
  { code: 'LS', name: '賴索托', en: 'Lesotho', dialCode: '+266' },
  { code: 'LR', name: '賴比瑞亞', en: 'Liberia', dialCode: '+231' },
  { code: 'LY', name: '利比亞', en: 'Libya', dialCode: '+218' },
  { code: 'LI', name: '列支敦斯登', en: 'Liechtenstein', dialCode: '+423' },
  { code: 'LT', name: '立陶宛', en: 'Lithuania', dialCode: '+370' },
  { code: 'LU', name: '盧森堡', en: 'Luxembourg', dialCode: '+352' },
  { code: 'MG', name: '馬達加斯加', en: 'Madagascar', dialCode: '+261' },
  { code: 'MW', name: '馬拉威', en: 'Malawi', dialCode: '+265' },
  { code: 'MY', name: '馬來西亞', en: 'Malaysia', dialCode: '+60' },
  { code: 'MV', name: '馬爾地夫', en: 'Maldives', dialCode: '+960' },
  { code: 'ML', name: '馬利', en: 'Mali', dialCode: '+223' },
  { code: 'MT', name: '馬爾他', en: 'Malta', dialCode: '+356' },
  { code: 'MH', name: '馬紹爾群島', en: 'Marshall Islands', dialCode: '+692' },
  { code: 'MR', name: '茅利塔尼亞', en: 'Mauritania', dialCode: '+222' },
  { code: 'MU', name: '模里西斯', en: 'Mauritius', dialCode: '+230' },
  { code: 'MX', name: '墨西哥', en: 'Mexico', dialCode: '+52' },
  { code: 'FM', name: '密克羅尼西亞', en: 'Micronesia', dialCode: '+691' },
  { code: 'MD', name: '摩爾多瓦', en: 'Moldova', dialCode: '+373' },
  { code: 'MC', name: '摩納哥', en: 'Monaco', dialCode: '+377' },
  { code: 'MN', name: '蒙古', en: 'Mongolia', dialCode: '+976' },
  { code: 'ME', name: '蒙特內哥羅', en: 'Montenegro', dialCode: '+382' },
  { code: 'MA', name: '摩洛哥', en: 'Morocco', dialCode: '+212' },
  { code: 'MZ', name: '莫三比克', en: 'Mozambique', dialCode: '+258' },
  { code: 'MM', name: '緬甸', en: 'Myanmar', dialCode: '+95' },
  { code: 'NA', name: '納米比亞', en: 'Namibia', dialCode: '+264' },
  { code: 'NR', name: '諾魯', en: 'Nauru', dialCode: '+674' },
  { code: 'NP', name: '尼泊爾', en: 'Nepal', dialCode: '+977' },
  { code: 'NL', name: '荷蘭', en: 'Netherlands', dialCode: '+31' },
  { code: 'NZ', name: '紐西蘭', en: 'New Zealand', dialCode: '+64' },
  { code: 'NI', name: '尼加拉瓜', en: 'Nicaragua', dialCode: '+505' },
  { code: 'NE', name: '尼日', en: 'Niger', dialCode: '+227' },
  { code: 'NG', name: '奈及利亞', en: 'Nigeria', dialCode: '+234' },
  { code: 'MK', name: '北馬其頓', en: 'North Macedonia', dialCode: '+389' },
  { code: 'NO', name: '挪威', en: 'Norway', dialCode: '+47' },
  { code: 'OM', name: '阿曼', en: 'Oman', dialCode: '+968' },
  { code: 'PK', name: '巴基斯坦', en: 'Pakistan', dialCode: '+92' },
  { code: 'PW', name: '帛琉', en: 'Palau', dialCode: '+680' },
  { code: 'PA', name: '巴拿馬', en: 'Panama', dialCode: '+507' },
  { code: 'PG', name: '巴布亞紐幾內亞', en: 'Papua New Guinea', dialCode: '+675' },
  { code: 'PY', name: '巴拉圭', en: 'Paraguay', dialCode: '+595' },
  { code: 'PE', name: '秘魯', en: 'Peru', dialCode: '+51' },
  { code: 'PH', name: '菲律賓', en: 'Philippines', dialCode: '+63' },
  { code: 'PL', name: '波蘭', en: 'Poland', dialCode: '+48' },
  { code: 'PT', name: '葡萄牙', en: 'Portugal', dialCode: '+351' },
  { code: 'QA', name: '卡達', en: 'Qatar', dialCode: '+974' },
  { code: 'RO', name: '羅馬尼亞', en: 'Romania', dialCode: '+40' },
  { code: 'RU', name: '俄羅斯', en: 'Russia', dialCode: '+7' },
  { code: 'RW', name: '盧安達', en: 'Rwanda', dialCode: '+250' },
  { code: 'KN', name: '聖克里斯多福及尼維斯', en: 'Saint Kitts and Nevis', dialCode: '+1869' },
  { code: 'LC', name: '聖露西亞', en: 'Saint Lucia', dialCode: '+1758' },
  { code: 'VC', name: '聖文森及格瑞那丁', en: 'Saint Vincent and the Grenadines', dialCode: '+1784' },
  { code: 'WS', name: '薩摩亞', en: 'Samoa', dialCode: '+685' },
  { code: 'SM', name: '聖馬利諾', en: 'San Marino', dialCode: '+378' },
  { code: 'ST', name: '聖多美普林西比', en: 'São Tomé and Príncipe', dialCode: '+239' },
  { code: 'SA', name: '沙烏地阿拉伯', en: 'Saudi Arabia', dialCode: '+966' },
  { code: 'SN', name: '塞內加爾', en: 'Senegal', dialCode: '+221' },
  { code: 'RS', name: '塞爾維亞', en: 'Serbia', dialCode: '+381' },
  { code: 'SC', name: '塞席爾', en: 'Seychelles', dialCode: '+248' },
  { code: 'SL', name: '獅子山', en: 'Sierra Leone', dialCode: '+232' },
  { code: 'SK', name: '斯洛伐克', en: 'Slovakia', dialCode: '+421' },
  { code: 'SI', name: '斯洛維尼亞', en: 'Slovenia', dialCode: '+386' },
  { code: 'SB', name: '索羅門群島', en: 'Solomon Islands', dialCode: '+677' },
  { code: 'SO', name: '索馬利亞', en: 'Somalia', dialCode: '+252' },
  { code: 'ZA', name: '南非', en: 'South Africa', dialCode: '+27' },
  { code: 'SS', name: '南蘇丹', en: 'South Sudan', dialCode: '+211' },
  { code: 'ES', name: '西班牙', en: 'Spain', dialCode: '+34' },
  { code: 'LK', name: '斯里蘭卡', en: 'Sri Lanka', dialCode: '+94' },
  { code: 'SD', name: '蘇丹', en: 'Sudan', dialCode: '+249' },
  { code: 'SR', name: '蘇利南', en: 'Suriname', dialCode: '+597' },
  { code: 'SE', name: '瑞典', en: 'Sweden', dialCode: '+46' },
  { code: 'CH', name: '瑞士', en: 'Switzerland', dialCode: '+41' },
  { code: 'SY', name: '敘利亞', en: 'Syria', dialCode: '+963' },
  { code: 'TJ', name: '塔吉克', en: 'Tajikistan', dialCode: '+992' },
  { code: 'TZ', name: '坦尚尼亞', en: 'Tanzania', dialCode: '+255' },
  { code: 'TH', name: '泰國', en: 'Thailand', dialCode: '+66' },
  { code: 'TL', name: '東帝汶', en: 'Timor-Leste', dialCode: '+670' },
  { code: 'TG', name: '多哥', en: 'Togo', dialCode: '+228' },
  { code: 'TO', name: '東加', en: 'Tonga', dialCode: '+676' },
  { code: 'TT', name: '千里達及托巴哥', en: 'Trinidad and Tobago', dialCode: '+1868' },
  { code: 'TN', name: '突尼西亞', en: 'Tunisia', dialCode: '+216' },
  { code: 'TR', name: '土耳其', en: 'Turkey', dialCode: '+90' },
  { code: 'TM', name: '土庫曼', en: 'Turkmenistan', dialCode: '+993' },
  { code: 'TV', name: '吐瓦魯', en: 'Tuvalu', dialCode: '+688' },
  { code: 'UG', name: '烏干達', en: 'Uganda', dialCode: '+256' },
  { code: 'UA', name: '烏克蘭', en: 'Ukraine', dialCode: '+380' },
  { code: 'AE', name: '阿拉伯聯合大公國', en: 'United Arab Emirates', dialCode: '+971' },
  { code: 'UY', name: '烏拉圭', en: 'Uruguay', dialCode: '+598' },
  { code: 'UZ', name: '烏茲別克', en: 'Uzbekistan', dialCode: '+998' },
  { code: 'VU', name: '萬那杜', en: 'Vanuatu', dialCode: '+678' },
  { code: 'VE', name: '委內瑞拉', en: 'Venezuela', dialCode: '+58' },
  { code: 'VN', name: '越南', en: 'Vietnam', dialCode: '+84' },
  { code: 'YE', name: '葉門', en: 'Yemen', dialCode: '+967' },
  { code: 'ZM', name: '尚比亞', en: 'Zambia', dialCode: '+260' },
  { code: 'ZW', name: '辛巴威', en: 'Zimbabwe', dialCode: '+263' },
]

/**
 * 根據語系取得國家顯示名稱
 * @param {Object} country - country object from countries array
 * @param {string} locale - current locale (e.g. 'zh-TW', 'en')
 */
export function getCountryName(country, locale) {
  if (locale === 'en') return country.en
  return country.name
}

export function getDialCodeByCode(code) {
  const country = countries.find(c => c.code === code)
  return country ? country.dialCode : ''
}
